INPUT_SIZE = 320

CONFIDENCE_THRESHOLD = 0.27
NMS_THRESHOLD = 0.2

FONT_COLOR = (0, 0, 255)
FONT_SIZE = 0.5
FONT_THICKNESS = 1

CLASSES_FILE = "./MODEL/coco.names"
REQUIRED_CLASS_INDEX = [2, 3, 5, 7]

MODEL_CONFIG = './MODEL/yolov4.cfg'
MODEL_WEIGHTS = './MODEL/yolov4.weights'
